### ISSUE TITLE
The username field is empty

### ISSUE THREAD

**Issue by thevelop** [michielvaneerd/api-bearer-auth#1]
Hi,

I don't know is this is an issue or what.

So, I'm trying to login via your tool and always return same code:

{"code":"empty_username","message":"Error<\/strong>: The username field is empty.","data":null,"additional_errors":[{"code":"empty_password","message":"Error<\/strong>: The password field is empty.","data":null}]}

I'm sending and CURL POST request with a two fields array:

username:value, password:value

So I cannot login.

Am I doing well?

**Comment by michielvaneerd** [comment]
Hi,

You have to send JSON in the body like this:

`{"username": "my_username", "password": "my_password"}`

**Comment by thevelop** [comment]
Thank you!

I finally try with another tool, so I found the solution for your tool and other in my shared hosting.

Mod_security bans request. Mod_security ID 33339 rule. I make an IP whitelist and now it works.

So, in addition I have a new rule in my .htaccess file:

`<IfModule mod_rewrite.c>
RewriteEngine On

RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

RewriteBase /
RewriteRule ^index\.php$ - [L]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>`

Now, I'm returning to install your tool because I prefer it.

Many thanks!

**Comment by michielvaneerd** [comment]
OK, glad it's working and thanks for getting back with your solution!

**Comment by thevelop** [comment]
Thanks dude!
